### ISSUE TITLE
build: the workspace needs a `rust-version` floor — it does not compile on rustc 1.94

### ISSUE THREAD

**Issue by rexlunae** [rexlunae/rython#208]
Minor, found while setting up the numpy evaluation (#191) on a container whose pinned `stable` was 1.94.1.

`rust-toolchain.toml` pins `channel = "stable"`, and CI uses `toolchain: stable`, so CI always gets the newest release and never sees this. But `python-ast` uses `if let` match guards, which are not stable in 1.94:

```
error[E0658]: `if let` guards are experimental
    --> crates/python-ast/src/ast/tree/call.rs:3808:33
    --> crates/python-ast/src/ast/tree/call.rs:3941:33
    --> crates/python-ast/src/ast/tree/call.rs:3979:33
    --> crates/python-ast/src/ast/tree/class_def.rs:2298:21
    --> crates/python-ast/src/ast/tree/class_def.rs:2319:21
```

`rustup update stable` to 1.98.0 fixes it. Nothing in the tree says which release is the floor, so anyone on a slightly older stable — a distro toolchain, a pinned CI image, a container that has not updated — gets five `E0658`s with no hint that the toolchain is the problem.

A `rust-version` in `[workspace.package]` would turn that into cargo's "package requires rustc 1.9x or newer" message. The crates are published, so it also affects downstream consumers resolving `python-ast` / `stdpython` from the registry.

I have not bisected the exact minimum — worth setting it to whichever release stabilized `if_let_guard` (and checking whether anything else in the tree needs newer).
